# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-P4ts8ofeaaheUX7crJ2sBd5Qap0H75
"""

!pip install streamlit pyngrok scikit-learn pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.naive_bayes import MultinomialNB
# import streamlit as st
# 
# # Load data
# data = pd.read_csv("spam.csv")
# data.drop_duplicates(inplace=True)
# data['Category'] = data['Category'].replace(['ham', 'spam'], ['Not Spam', 'Spam'])
# 
# mess = data['Message']
# cat = data['Category']
# 
# mess_train, mess_test, cat_train, cat_test = train_test_split(mess, cat, test_size=0.2, random_state=42)
# 
# cv = CountVectorizer(stop_words='english')
# features_train = cv.fit_transform(mess_train)
# features_test = cv.transform(mess_test)
# 
# model = MultinomialNB()
# model.fit(features_train, cat_train)
# 
# def predict(message):
#     input_message = cv.transform([message]).toarray()
#     result = model.predict(input_message)
#     return result
# 
# st.header('Spam Detection')
# input_messge = st.text_input('Enter Message Here')
# 
# if st.button('Validate'):
#     output = predict(input_messge)
#     st.text(str(output[0]))

from google.colab import files
files.upload()  # select your spam.csv here

from pyngrok import ngrok
import subprocess, time

# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
ngrok.set_auth_token("YOUR_AUTHTOKEN")

subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"])
time.sleep(3)
public_url = ngrok.connect(8501)
print("🔗 Open this URL:", public_url)